config/routes.rb
Scrumwich::Application.routes.draw do

  root 'projects#index'

  resources :projects, only: [:index, :show, :new, :create] do
    resources :people, controller: 'projects/people', only: [:create, :destroy]

    resources :entries, controller: 'projects/entries' do
      collection do
        get :today
      end
    end

    member do
      get :join
    end
  end

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :person
  belongs_to :project

  validates :yesterday, presence: true, length: { maximum: 560 }
  validates :today, presence: true, length: { maximum: 560 }
  validates :block, length: { maximum: 560 }

  def self.for_today
    Entry.for_day DateTime.now
  end

  scope :for_day, -> (day) { where('created_at BETWEEN ? AND ?', day.beginning_of_day, day.end_of_day) }

end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  belongs_to :project
  belongs_to :person

  validates :code, presence: true

  before_create :create_code

  def create_code
    self.code = SecureRandom.uuid
  end
end

app/models/person.rb
class Person < ActiveRecord::Base
  include Gravtastic
  gravtastic

  has_many :entries
  has_many :invitations
  has_and_belongs_to_many :projects

  validates :name, presence: true, length: { maximum: 560 }
  validates :email, presence: true, length: { maximum: 560 }
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :owner, class_name: :Person
  has_many :entries
  has_and_belongs_to_many :people, -> { uniq }

  validates :name, presence: true, length: { maximum: 40 }
  validates :owner, presence: true

  def owner=(val)
    people << val
    super val
  end

  def last_10_days
    (0..9).map do |days_back|
      date = DateTime.now - days_back
      results = entries.for_day date
      results.empty? ? date : results
    end
  end

  def invite_people(emails)
    emails.each do |email|
      invite_person email
    end
  end

  def invite_person(email)
    person = Person.find_by email: email
    if person.nil?
      person = Person.create! name: email, email: email
    end
    unless self.people.include? person
      self.people << person
      invitation = create_invitation person
      ProjectMailer.invite_member invitation
    end
  end

  def create_invitation(person)
    inv = Invitation.new project: self, person: person
    inv.create_code
    inv.save
    inv
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :load_current_user

  protected
    def load_current_user
      @user = current_user
    end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def today
    @entries = Entry.for_today
  end

  def new
    @person_name = cookies[:person_name]
    @person_email = cookies[:person_email]
    @entry = Entry.new
  end

  def create
    p = Person.find_by(name: params[:person_name], email: params[:person_email])
    if p.nil?
      new_person = Person.new(name: params[:person_name], email: params[:person_email])
      if !new_person.save
        @person_errors = new_person.errors.full_messages
        @entry = Entry.new
        render :new
        return
      end
      p = new_person
    end
    cookies[:person_name] = p.name
    cookies[:person_email] = p.email
    @entry = p.entries.build entry_params
    if @entry.save
      redirect_to today_entries_path
    else
      @entry_errors = @entry.errors.full_messages
      render :new
    end
  end

  def show
    @day = DateTime.strptime(params[:id], "%m-%d-%Y")
    @entries = Entry.for_day @day
  end

  private
    def entry_params
      params.require(:entry).permit(:yesterday, :today, :block)
    end
end

app/controllers/projects/entries_controller.rb
class Projects::EntriesController < ApplicationController
  before_action :get_project

  def today
    @entries = Entry.for_today
  end

  def new
    @person_name = cookies[:person_name]
    @person_email = cookies[:person_email]
    @entry = Entry.new
  end

  def create
    cookies[:person_email] = current_user.email
    @entry = @project.entries.build entry_params
    @entry.person = current_user
    if @entry.save
      redirect_to today_project_entries_path
    else
      @entry_errors = @entry.errors.full_messages
      render :new
    end
  end

  def show
    @day = DateTime.strptime(params[:id], "%m-%d-%Y")
    @entries = Entry.for_day @day
  end

  private
    def entry_params
      params.require(:entry).permit(:yesterday, :today, :block)
    end

    def get_project
      @project = Project.find_by(id: params[:project_id])
    end
end

app/controllers/projects/people_controller.rb
class Projects::PeopleController < ApplicationController
  include ProjectsHelper

  def destroy
    if find_project.nil? or find_person.nil?
      redirect_to status: 404
    else
      @project.people.delete @person
      respond_to do |format|
        format.html { redirect_to @project }
        format.json { render nothing: true }
      end
    end
  end

  def create
    if find_project.nil?
      redirect_to status: 404
    else
      @project.invite_people(emails_from_lines params[:invitations])
      respond_to do |format|
        format.html { redirect_to @project }
        format.json { render nothing: true }
      end
    end
  end

  private
    def find_project
      @project = Project.where(id: params[:project_id]).first
    end

    def find_person
      @person = @project.people.where(id: params[:id]).first
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  include ProjectsHelper

  before_action :find_project, only: [:show, :join]

  def index
    unless current_user
      render template: "projects/no_user"
      return
    end
  end

  def show
  end

  def new
    unless current_user
      render template: "projects/no_user"
      return
    end
    @project = Project.new
  end

  def create
    unless current_user
      render template: "projects/no_user"
      return
    end
    @project = current_user.projects.build safe_params
    @project.owner = current_user
    if @project.save
      redirect_to @project
    else
      render :new
    end
  end

  def join
    if find_invitation.nil? or @invitation.project_id != @project.id
      redirect_to status: 404
      return
    end
    store_token @invitation.person.email
    @invitation.destroy
  end

  private
    def find_project
      @project = Project.find_by id: params[:id]
    end

    def safe_params
      params.require(:project).permit :name
    end

    def find_invitation
      @invitation = Invitation.find_by code: params[:code]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  attr_accessor :current_user

  def current_user
    return @current_user if @current_user
    email = retrieve_token
    @current_user = Person.find_by(email: email)
    @current_user
  end

  def long_formatted_date date
    date.strftime "%B %d, %Y"
  end

  def short_formatted_date date
    date.strftime "%m-%d-%Y"
  end

  protected
  def store_token(token)
    cookies.permanent[:person_email] = token
  end

  private
  def retrieve_token
    cookies[:person_email]
  end

end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def emails_from_lines(text)
    text.lines.map(&:strip)
  end
end

app/views/entries/new.html.erb
<% content_for :title do %>Entry For Today<% end %>

<div class="row">
  <h1 class="columns">Entry For Today</h1>
</div>

<% 
    @person_errors ||= [] 
    @entry_errors ||= []
%>

<% if @person_errors.any? or @entry_errors.any? %>
  <div class="row row-error">
    <h2>Errors</h2>
    <ul>
      <% 
        all_errors = @entry_errors.concat @person_errors
        all_errors.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @entry do |f| %>
  <div class="row">
    <div class="large-6 columns">
      <%= label_tag :person_name, "Your Name" %>
      <%= text_field_tag :person_name, @person_name %>
    </div>
  </div>
  <div class="row">
    <div class="large-6 columns">
      <%= label_tag :person_email, "Your Email" %>
      <%= text_field_tag :person_email, @person_email %>
      <span class="info">Your email address will be used to generate your avatar. <a href="http://gravatar.com">Set it up over here</a>.</span>
    </div>
  </div>
  <div class="row">
    <div class="large-6 columns">
      <%= f.label :yesterday, "What Did You Work On Yesterday?" %>
      <%= f.text_area :yesterday, class: "data-entry" %>
    </div>
  </div>
  <div class="row">
    <div class="large-6 columns">
      <%= f.label :today, "What Will You Work On Today?" %>
      <%= f.text_area :today, class: "data-entry" %>
    </div>
  </div>
  <div class="row">
    <div class="large-6 columns">
      <%= f.label :block, "Any Blocks?" %>
      <%= f.text_area :block, class: "data-entry" %>
      <span class="info">Leave this blank if there were none.</span>
    </div>
  </div>
  <div class="row">
    <div class="large-12 columns">
      <%= f.submit "Add", class: "button" %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "" %> -- Scrumwich</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  <nav class="top-bar" data-topbar>
    <ul class="title-area">
      <li class="name">
        <h1><%= link_to "Today", root_url %></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <li class="has-dropdown">
          <a href="">Projects</a>
          <ul class="dropdown">
            <% if @user %>
              <% @user.projects.each do |proj| %>
                <li><%= link_to proj.name, proj %></li>
              <% end %>
              <li class="divider"></li>
              <li class="new_project"><%= link_to "New Project", new_project_path %></li>
            <% end %>
          </ul>
        </li>
        <li class="active">
          <% if @project and @project.id %>
            <%= link_to "Add Today's Entry", new_project_entry_path(project_id: @project.id) %>
          <% end %>
        </li>
      </ul>
    </section>
  </nav>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/projects/entries/_entry.html.erb
<div class="row row-scrum <%= entry.block.empty? ? "" : "row-blocked" %>">
  <div class="small-2 large-2 columns">
    <%= image_tag entry.person.gravatar_url(:rating => 'PG', :secure => true) %>
    <br />
    <a href="mailto:<%= entry.person.email %>"><%= entry.person.name %></a>
  </div>
  <div class="small-4 large-4 columns">
    <%= simple_format entry.yesterday %>
  </div>
  <div class="small-3 large-3 columns">
    <%= simple_format entry.today %>
  </div>
  <div class="small-3 large-3 columns block">
    <%= simple_format entry.block %>
  </div>
</div>

app/views/projects/entries/_grid_header.html.erb
<div class="row row-header">
  <div class="small-2 large-2 columns">
    Person
  </div>
  <div class="small-4 large-4 columns">
    Worked on yesterday
  </div>
  <div class="small-3 large-3 columns">
    Working on today
  </div>
  <div class="small-3 large-3 columns">
    Blocks
  </div>
</div>

app/views/projects/entries/new.html.erb
<% content_for :title do %>Entry For Today<% end %>

<div class="row">
  <h1 class="columns">Entry For Today</h1>
</div>

<% 
    @person_errors ||= [] 
    @entry_errors ||= []
%>

<% if @person_errors.any? or @entry_errors.any? %>
  <div class="row row-error">
    <h2>Errors</h2>
    <ul>
      <% 
        all_errors = @entry_errors.concat @person_errors
        all_errors.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @entry, url: project_entries_path(project_id: @project.id) do |f| %>
  <div class="row">
    <div class="large-6 columns">
      <%= f.label :yesterday, "What Did You Work On Yesterday?" %>
      <%= f.text_area :yesterday %>
    </div>
  </div>
  <div class="row">
    <div class="large-6 columns">
      <%= f.label :today, "What Will You Work On Today?" %>
      <%= f.text_area :today %>
    </div>
  </div>
  <div class="row">
    <div class="large-6 columns">
      <%= f.label :block, "Any Blocks?" %>
      <%= f.text_area :block %>
      <span class="info">Leave this blank if there were none.</span>
    </div>
  </div>
  <div class="row">
    <div class="large-12 columns">
      <%= f.submit "Add", class: "button" %>
    </div>
  </div>
<% end %>

app/views/projects/entries/show.html.erb
<% content_for :title do %><%= @day.strftime("%m-%d-%Y") %><% end %>

<%= render partial: "shared/date_header", locals: {d: @day} %>

<%= render partial: "grid_header" %>

<%= render @entries   %>

app/views/projects/entries/today.html.erb
<% content_for :title do %>Today<% end %>

<%= render partial: "shared/date_header", locals: {d: DateTime.now} %>

<%= render partial: "grid_header" %>

<%= render @entries   %>

app/views/projects/index.html.erb
<% content_for :title do %>Your Projects<% end %>

<div class="row">
  <div class="large-8 offset-2">
    <h2>Available Projects</h2>
    <% @user.projects.each do |proj| %>
      <div class="row row-project"><%= link_to proj.name, proj %></div>
    <% end %>
    <%= link_to "Create a Project", new_project_path, class: "button" %>
  </div>
</div>

app/views/projects/join.html.erb
<h2>Join <%= @project.name%></h2>

app/views/projects/new.html.erb
<% content_for :title do %>New Project<% end %>

<h2>New Project</h2>
<%= form_for @project do |f| %>
  <% if @project.errors.any? %>
    <div class="row row-error">
      <h2>Errors</h2>
      <ul>
        <% 
          @project.errors.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>

  <% end %>

  <div class="row">
    <div class="large-6 columns">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="row">
      <div class="large-12 columns">
        <%= f.submit "Add", class: "button" %>
      </div>
    </div>
  </div>
<% end %>

app/views/projects/no_user.html.erb
<div class="row">
  <div class="large-8 offset-2">
    <h2>You Need an Account</h2>
    <p>Scrumwich works by invitations. Ask your admin for one.</p>
  </div>
</div>

app/views/projects/show.html.erb
<% content_for :title do %><%= @project.name %><% end %>

<div class="columns">
  <h2><%= @project.name %></h2>
  <hr />
</div>

<section class="large-8 small-12 columns grid grid-striped">
  <h4>The Last 10 Days</h4>
  <% @project.last_10_days.each do |entry| %>
    <div class="row row-day">
    <% if entry.class == DateTime %>
      <div class="large-8 small-8 columns">
        <%= link_to (long_formatted_date entry), project_entry_path(project_id: @project.id, id: short_formatted_date(entry)) %>
      </div>
      <div class="large-4 small-4 columns">
        0
      </div>
    <% else %>
      <div class="large-8 small-8 columns">
        <%= link_to long_formatted_date(entry.first.created_at), project_entry_path(project_id: @project.id, id: short_formatted_date(entry.first.created_at)) %>
      </div>
      <div class="large-4 small-4 columns">
        <%= entry.count %>
      </div>
    <% end %>
    </div>
  <% end %>
</section>
<aside class="large-4 small-12 columns">
  <h3>People in this Project</h3>
  <ul class="people">
    <% @project.people.each do |person| %>
      <li class="person">
        <%= image_tag person.gravatar_url(rating: 'PG', secure: true, size: 24) %>
        <%= link_to person.name, "mailto:#{person.email}" %>
        <%= link_to project_person_path(id: person.id, project_id: @project.id), method: :delete, data: { confirm: "Are you sure?" }, class: "remove_person right" do %>
          &times;
        <% end %>
      </li>
    <% end %>
    <li><a href="#" data-dropdown="invite_people">Invite People</a>
      <div id="invite_people" class="f-dropdown content" data-dropdown-content>
        <%= form_tag project_people_path(project_id: @project.id) do %>
          <label for="invitations">Emails of people to invite (one per line)</label>
          <%= text_area_tag :invitations %>
          <input type="submit" value="Invite" class="tiny button" />
        <% end %>
      </div>
    
    </li>
  </ul>
</aside>

app/views/shared/_date_header.html.erb
<div class="date-header">
  <% tomorrow = d+1 %>
  <h1><%= link_to "«", project_entry_path(project_id: @project.id, id: (d-1).strftime("%m-%d-%Y")) %><%= d.strftime("%B %d, %Y") %>
  <% if tomorrow < DateTime.now %>
    <%= link_to "»", project_entry_path(project_id: @project.id, id: tomorrow.strftime("%m-%d-%Y")) %>
  <% end %>
  </h1>
</div>